### ISSUE TITLE
Crash when exporting large excel file

### ISSUE THREAD

**Issue by caarmen** [caarmen/network-monitor#60]
Could reproduce this on a Nexus One emulator, exporting about 7100 rows:

```
05-30 13:14:52.944 10257 10460 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-30 13:14:52.944 10257 10460 E AndroidRuntime: java.lang.RuntimeException: An error occured while executing doInBackground()
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:200)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:274)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:125)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:308)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1019)
05-30 13:14:52.944 10257 10460 E AndroidRuntime: Caused by: java.lang.OutOfMemoryError
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at jxl.write.biff.WritableSheetImpl.getRowRecord(WritableSheetImpl.java:1223)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at jxl.write.biff.WritableSheetImpl.addCell(WritableSheetImpl.java:1151)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at ca.rmen.android.networkmonitor.app.dbops.backend.export.ExcelExport.insertCell(ExcelExport.java:176)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at ca.rmen.android.networkmonitor.app.dbops.backend.export.ExcelExport.writeRow(ExcelExport.java:103)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at ca.rmen.android.networkmonitor.app.dbops.backend.export.TableFileExport.export(TableFileExport.java:112)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at ca.rmen.android.networkmonitor.app.dbops.backend.export.ExcelExport.export(ExcelExport.java:54)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at ca.rmen.android.networkmonitor.app.dbops.backend.export.TableFileExport.execute(TableFileExport.java:80)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at ca.rmen.android.networkmonitor.app.dbops.backend.export.ExcelExport.execute(ExcelExport.java:54)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at ca.rmen.android.networkmonitor.app.dbops.backend.export.TableFileExport.execute(TableFileExport.java:48)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at ca.rmen.android.networkmonitor.app.dbops.ui.DBOpAsyncTask.doInBackground(DBOpAsyncTask.java:74)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at ca.rmen.android.networkmonitor.app.dbops.ui.Share$2.doInBackground(Share.java:121)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at ca.rmen.android.networkmonitor.app.dbops.ui.Share$2.doInBackground(Share.java:112)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:185)
05-30 13:14:52.944 10257 10460 E AndroidRuntime:        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
```

**Comment by caarmen** [comment]
Will be in 1.20.1
