### ISSUE TITLE
Eventbus crash

### ISSUE THREAD

**Issue by caarmen** [caarmen/network-monitor#85]
```
Caused by: java.lang.IllegalArgumentException: Missing event handler for an annotated method. Is class ca.rmen.android.networkmonitor.app.log.LogActivity registered?
	at com.squareup.otto.Bus.unregister(Bus.java:290)
	at ca.rmen.android.networkmonitor.app.log.LogActivity.onPause(LogActivity.java:114)
	at android.app.Activity.performPause(Activity.java:5382)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1239)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3224)
	... 12 more
```

Let's try to replace otto with greenrobot to see if that fixes the problem.

**Comment by caarmen** [comment]
Fixed in 1.28.10
